apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-data
  labels:
    app.kubernetes.io/name: secure-supply-chain-inventory
    app.kubernetes.io/instance: base
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
